### ISSUE TITLE
repository local wordlists

### ISSUE THREAD

**Issue by ivimla** [Sephley/WPbruteforcer#5]
since you have moved to dynamic word-lists, which are downloaded on the fly (https://github.com/Sephley/WPbruteforcer/blob/dev/hydra.sh#L44-L46), why are they still in the [repo](https://github.com/Sephley/WPbruteforcer/tree/dev/wordlists)? is this intentional?

**Comment by Sephley** [comment]
Yes, it was intentional. I am working on using the gitignore file to make sure they dont automatically get downloaded when the repo is cloned.
I felt like it was more professional / secure to have them in my own repo, but correct me if I'm wrong.
Obviously I need to make sure that the files don't get downloaded every time I run the script, but that is another matter.

**Comment by ivimla** [comment]
Hm let me put it this way.
They have to get downloaded anyways. So now the are being downloaded when the repository is cloned, and again when you run the script. It just seems redundant to it this way.
Either they are downloaded through git or the script does that job for you.

Regarding the gitignore. The gitignore contains a list of patterns which git should ignore when you are staging stuff in your local repository. For that, you would have to first delete the word-lists in the repository and then push those changes.
Let me know if I can help you with this in any way.
